services:
  mssqldb:
    container_name: database
    user: root
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=KingPrice@3214
    restart: unless-stopped
    ports:
      - "4001:1433"
    volumes:
      - mssql_storage:/var/opt/mssql/data

  seq:
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_LICENSE=trial
    restart: unless-stopped
    ports:
      - "4002:80"
    volumes:
      - seq_storage:/data

  kingpricedemo.webapi:
    container_name: webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - Serilog__WriteTo__0__Args__serverUrl=http://seq:80 
      - ScalarExplorer__Servers__0__Url=https://localhost:6001
      - ScalarExplorer__Servers__0__Description=Docker Hosted
      - ConnectionStrings__DefaultConnection=Data Source=mssqldb;Initial Catalog=KingPriceDemo;User ID=sa;Password=KingPrice@3214;TrustServerCertificate=True;Encrypt=false;
    depends_on:
      - mssqldb
      - seq
    ports:
      - "5001:8080"
      - "6001:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro